# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.25.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
vec = np.full(10, None)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
vec.nbytes

80

In [6]:
vec.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vec = np.full(10, None)
vec[4] = 1
vec

array([None, None, None, None, 1, None, None, None, None, None],
      dtype=object)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
#range?
vec = np.array(range(10,50))
vec
vec = np.arange(10, 50, 1)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
vec = np.flip(vec, axis = 0)
vec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
vec = np.array(range(0, 9))
vec = vec.reshape(3,3)
vec

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [12]:
vec = np.array([1,2,0,0,4,0])
vec.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [13]:
vec = np.identity(3)
vec

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [14]:
vec = np.random.rand(3,3,3)
vec

array([[[0.6905975 , 0.65180805, 0.1553764 ],
        [0.4902961 , 0.32943237, 0.06738207],
        [0.42723651, 0.10329418, 0.68113502]],

       [[0.98762933, 0.40750803, 0.23928207],
        [0.59126178, 0.81876493, 0.8306935 ],
        [0.60423425, 0.40313989, 0.8136884 ]],

       [[0.66500391, 0.32411744, 0.70296501],
        [0.17155643, 0.15474457, 0.48763575],
        [0.97907775, 0.20526396, 0.30131776]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [15]:
vec = np.random.rand(10, 10)
vec.max() #np.max(vec)
vec.min() #np.min(vec)


0.0337573993678576

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [16]:
vec = np.random.rand(30)
np.mean(vec)

0.5870659740008894

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [17]:
vec = np.ones((10,10))
vec[1:-1,1:-1] = 0
vec

#vec = np.zeros((9,9))
#vec = np.pad(vec, pad_width=1, mode='constant', constant_values=1)
#vec

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [18]:
vec = np.ones((5,5))
vec = np.pad(vec, pad_width=1, mode='constant', constant_values=0)
vec

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan + np.nan)
print(np.nan - np.nan)
print(np.nan * np.nan)
print(np.nan / np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
nan
nan
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [53]:
#np.tile?
vec = np.tile(['#', 'o'], (8,4))
print(vec)

[['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']
 ['#' 'o' '#' 'o' '#' 'o' '#' 'o']]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
100 - 7*8
#So is the element (2, 4, 5) = arr[1][3][4]

44

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
vec = np.tile(np.array([0,1]), (8,4))
vec

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
vec = np.random.rand(5,5)
print(vec)
vec = (vec - np.mean(vec))/np.std(vec)
print(vec)

[[0.27962893 0.60438286 0.86100753 0.05484174 0.31972999]
 [0.12293706 0.45828093 0.81247219 0.84637797 0.65993405]
 [0.50926488 0.82417001 0.38289867 0.39570278 0.55169433]
 [0.28863396 0.34173408 0.0249021  0.31074786 0.55569588]
 [0.07432427 0.53553777 0.08404371 0.37504589 0.87936141]]
[[-0.63538077  0.60387494  1.58315055 -1.49316506 -0.48235579]
 [-1.23331439  0.04635236  1.39794048  1.52732436  0.81585739]
 [ 0.24090629  1.44257914 -0.24130514 -0.19244484  0.40281637]
 [-0.60101772 -0.39838852 -1.60741421 -0.51663145  0.41808623]
 [-1.41882004  0.3411632  -1.38173078 -0.27127121  1.65318863]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
meu_dtype = np.dtype([('b1', 'U1'),
                      ('b2', 'U2'),
                      ('b3', 'U3'),
                      ('b4', 'U4')])
meu_dtype

dtype([('b1', '<U1'), ('b2', '<U2'), ('b3', '<U3'), ('b4', '<U4')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
m1 = np.random.rand(5,3)
m2 = np.random.rand(3, 2)

vec = m1 @ m2
print(vec)
vec = np.matmul(m1, m2)
print(vec)

[[0.82827491 1.62494847]
 [0.54827045 1.20902015]
 [0.14395618 1.11499969]
 [0.77801858 1.62464472]
 [0.76940723 1.0557857 ]]
[[0.82827491 1.62494847]
 [0.54827045 1.20902015]
 [0.14395618 1.11499969]
 [0.77801858 1.62464472]
 [0.76940723 1.0557857 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
vec = np.random.randint(0, 20, size=(20))
print(vec)

vec1 = np.copy(vec)
vec1[(vec1 > 3) & (vec1 < 8)] = -vec1[(vec1 > 3) & (vec1 < 8)]
print(vec1)



[ 4 14  2  5 13 12  8  6 18 17  3 16 17 12  4  5 16 12 13 14]
[-4 14  2 -5 13 12  8 -6 18 17  3 16 17 12 -4 -5 16 12 13 14]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
#9
#10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
Z = np.arange(11)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#Z<Z>Z

[ 0  1  2  3  4  5  6  7  8  9 10]
[          1           1           4          27         256        3125
       46656      823543    16777216   387420489 10000000000]
[  0   1   2   4   8  16  32  64 128 256 512]
[False False False False False False False False False False False]
[0. +0.j 0. +1.j 0. +2.j 0. +3.j 0. +4.j 0. +5.j 0. +6.j 0. +7.j 0. +8.j
 0. +9.j 0.+10.j]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-7.50193442  6.09673127 -0.50589543 -1.23773624  6.69532959  1.68866039
 -4.38814941  0.30803194  3.94686721 -2.74339441]
[-8.  7. -1. -2.  7.  2. -5.  1.  4. -3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
v1 = np.random.randint(0, 101, size=(20))
v2 = np.random.randint(0, 101, size=(20))
print(v1)
print(v2)

vec = np.copy(v1)

vec[(v1 != v2)] = 0
vec

#vec = np.intersect1d(v1, v2)

[62 61 58  3 22 16 21 72 90 26 17 41 54 74 27 17 69 36 52  1]
[ 37  85  61  60  82  60  94  11  35 100  18  16  19   9  41  92  17  37
 100  93]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [30]:
#defaults = np.seterr(all="ignore") #Set chaos
#_ = np.seterr(**defaults) #Turn to normal

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [31]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2024-07-22
2024-07-23
2024-07-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [32]:
dates = np.arange('2016-07-01', '2016-07-31', dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [33]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
print(A)
print(B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[[0.33763315 0.37044493 0.19954201]
 [0.88207879 0.43839777 0.82605955]
 [0.19521942 0.80476905 0.08488673]]
[[0.80015702 0.65669934 0.82947176]
 [0.20804129 0.46556272 0.67157556]
 [0.31551482 0.88315853 0.19631096]]


array([[-0.19207784, -0.19025019, -0.10266574],
       [-0.4807859 , -0.19814713, -0.61856789],
       [-0.04985262, -0.67919594, -0.01193498]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [34]:
vec = np.random.uniform(0, 10, 10) * np.pi * np.pi
print(vec)

print(vec - vec%1)
print(vec // 1)
print(np.floor(vec))
print(vec.astype(int))
print(np.trunc(vec))


[32.74218941 70.46219802 29.02230682 90.99068689 30.32122464 76.36778525
 26.49171306 44.17086804  3.80119943 90.57473794]
[32. 70. 29. 90. 30. 76. 26. 44.  3. 90.]
[32. 70. 29. 90. 30. 76. 26. 44.  3. 90.]
[32. 70. 29. 90. 30. 76. 26. 44.  3. 90.]
[32 70 29 90 30 76 26 44  3 90]
[32. 70. 29. 90. 30. 76. 26. 44.  3. 90.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [35]:
vec = np.arange(0, 5)
vec = np.tile(vec, (5,1))
vec

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [36]:
vec = np.linspace(0, 1, 12, endpoint=True)
vec = vec[1:-1]
vec

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [37]:
vec = np.random.uniform(1, 10, 10)
vec.sort()
print(vec)

[2.09363115 2.63109549 3.52871836 4.78664749 5.4530523  6.07229886
 6.96043766 7.27249911 9.01894888 9.67576951]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [38]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [39]:
v1 = np.random.uniform(0, 10, 5)
v2 = np.random.uniform(0, 10, 5)

print(v1, v2)
print(v1 == v2)
print(v1 == v1)
print(v2 == v2)
print(np.all(v1 == v2))
print(np.all(v1 == v1))
print(np.all(v2 == v2))

[9.45746998 3.42118542 2.20424274 8.34432807 5.40260729] [1.33851499 0.92386562 2.75515594 6.58498584 5.74165444]
[False False False False False]
[ True  True  True  True  True]
[ True  True  True  True  True]
False
True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [40]:
v1 = np.random.randint(0, 101, size=(4,4))
print(v1)

v1.flags.writeable = False
#v1[0][0] = 0
v1.flags.writeable = True

[[47 10 99  1]
 [34 76 74  3]
 [41 11 52 90]
 [61 45 28 23]]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [41]:
v1 = np.random.uniform(-100, 100, size=(10,2))
print(v1)


r = np.sqrt(v1[:, 0]**2+v1[:, 1]**2)
#print(r)

# Calculate the angle (in radians)
theta = np.arctan2(v1[:, 1], v1[:, 0])
#print(theta)

polar_v1 = np.hstack((r, theta))
print(polar_v1)


[[-82.67325299  82.6413487 ]
 [-72.94218796  97.31323438]
 [-80.21905719  84.50715995]
 [ 51.73907298 -52.10128565]
 [-42.35605214  43.10358543]
 [ 65.81533484 -49.05221989]
 [ 73.23474513  33.58416735]
 [ -1.83256645 -89.89744817]
 [ 62.2005279   56.37798978]
 [-33.79358386 -72.90208799]]
[116.89507806 121.61590509 116.51848445  73.42666844  60.43140102
  82.08397271  80.56813384  89.91612473  83.94869506  80.35372265
   2.35638748   2.2140163    2.33016867  -0.78888632   2.3474475
  -0.64048681   0.42996811  -1.59117858   0.73633476  -2.0048591 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [42]:
v1 = np.random.randint(0, 101, size=(20))
print(v1)
v1[(v1 == v1.max())] = 0
print(v1)

#From the book
#v1[v1.argmax()] = 0
#print(v1)

#v1.argmax? # Return indices of the maximum values along the given axis.

[43 58 45 12 38 52 67  6 48 19 99 36 77 97  2 84 45  4  8 42]
[43 58 45 12 38 52 67  6 48 19  0 36 77 97  2 84 45  4  8 42]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [43]:
#Taken from the book
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [44]:
#v1 = np.random.randint(101, size=5)
#v2 = np.random.randint(101, size=5)
#print(v1, v2)



#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [45]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
   print(" ")
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
   print(" ")

-128
127
 
-2147483648
2147483647
 
-9223372036854775808
9223372036854775807
 
-3.4028235e+38
3.4028235e+38
1.1920929e-07
 
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16
 


#### 49. How to print all the values of an array? (★★☆)

In [46]:
#np.set_printoptions(threshold=float("inf"))

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [47]:
pos = np.zeros((5,5), [('x',int),('y',int)])
color = np.zeros((5,5), [('r',int),('g',int),('b',int)])


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [48]:
vec = np.random.randint(0, 101, size=(10,2))
print(vec)

v1 = np.sqrt(np.abs(vec[:, 0]**2 - vec[:, 1]**2))
print(v1)

[[ 17  66]
 [ 98  25]
 [ 32   1]
 [ 61  87]
 [ 23   8]
 [ 26 100]
 [ 73  11]
 [ 97   3]
 [ 76  65]
 [ 56  44]]
[63.77303505 94.75758545 31.98437118 62.03224968 21.56385865 96.56086164
 72.16647421 96.95359715 39.38273734 34.64101615]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [78]:
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

Y1 = np.copy(Z.view(np.int32))
Y1[:] = Z
print(Y1)

Y2 = np.copy(np.floor(Z).astype(np.int32))
print(Y2)

Y3 = np.copy(Z // 1).astype(np.int32)
print(Y3)

Y4 = np.copy(np.trunc(Z).astype(np.int32))
print(Y4)



[94.007614 80.30852  88.917145 93.51927  62.210682 22.128372 66.98216
 78.78036  16.825296 54.437466]
[94 80 88 93 62 22 66 78 16 54]
[94 80 88 93 62 22 66 78 16 54]
[94 80 88 93 62 22 66 78 16 54]
[94 80 88 93 62 22 66 78 16 54]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [87]:
#np.put?
#np.random.choice?
#np.random.Generator.choice?
Z = np.zeros((8,8)).astype(np.int32)
np.put(Z, np.random.choice(range(8*8), 4, replace=False), 18)
print(Z)

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 18]
 [ 0  0 18  0  0 18  0 18]
 [ 0  0  0  0  0  0  0  0]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)